<a href="https://colab.research.google.com/github/collinscolour/GoMyCodeDataScience/blob/main/learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1,2,7]])
print(a)

[[1 2 7]]


In [2]:
b=np.array([[3,4,],[3.5, 7.4, ], [3.3, 7.1, ], [3.9, 8.4, ]])
print(b)

[[3.  4. ]
 [3.5 7.4]
 [3.3 7.1]
 [3.9 8.4]]


HOW TO GET DIMENSION

In [3]:
a.ndim

2

HOW TO GET shape

In [4]:
a.shape

(1, 3)

In [6]:
b.shape

(4, 2)

HOW TO GET type

In [7]:
b.dtype

dtype('float64')

HOW TO GET size

In [8]:
a.nbytes

24

To get a specific element

In [9]:
#b=np.array([[3.0,4.0],[3.5, 7.4, ], [3.3, 7.1, ], [3.9, 8.4, ]])
b[2,1]
b[-1,1]
print(b)

[[3.  4. ]
 [3.5 7.4]
 [3.3 7.1]
 [3.9 8.4]]


To get a specific row

In [10]:
b[1,:]

array([3.5, 7.4])

To get a specific column

In [11]:
b[1:3, 0]

array([3.5, 3.3])

In [12]:
b[:, 1]

array([4. , 7.4, 7.1, 8.4])

Change element

In [13]:
b[2,0]= 22.5
print(b)

[[ 3.   4. ]
 [ 3.5  7.4]
 [22.5  7.1]
 [ 3.9  8.4]]


In [14]:
b[:, 1]= 22.9
print(b)
b[:, 1]= [1.0, 2.2, 3.0, 4.0]
print(b)

[[ 3.  22.9]
 [ 3.5 22.9]
 [22.5 22.9]
 [ 3.9 22.9]]
[[ 3.   1. ]
 [ 3.5  2.2]
 [22.5  3. ]
 [ 3.9  4. ]]


In [15]:
b = np.array([[[1,2],[3,4]], [[5,6],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [16]:
b[1,1]

array([6, 7])

In [17]:
b[1]

array([[5, 6],
       [6, 7]])

initializing array types

In [18]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.full((2,2,3), 22)

array([[[22, 22, 22],
        [22, 22, 22]],

       [[22, 22, 22],
        [22, 22, 22]]])

In [21]:
a=np.array([[1,2,3,4,5,6,7]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4]])

In [22]:
np.full(a.shape, 3)

array([[3, 3, 3, 3, 3, 3, 3]])

In [23]:
np.random.rand(2,4)

array([[0.10287838, 0.56115819, 0.7152758 , 0.50516661],
       [0.14173355, 0.5148619 , 0.65508167, 0.04882834]])

In [24]:
np.random.randint(5, size=(2,2))

array([[3, 1],
       [2, 1]])

In [25]:
np.random.randint(5,8, size=(2,4))

array([[7, 5, 6, 6],
       [6, 6, 6, 7]])

In [26]:
output= np.ones((5,5))
print(output)
z= np.zeros((3,3))
print(z)
z[1,1]= 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
